### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by NarenTheBeesechurgerMan** [Leviathan143/minecraft-quiverbow#19]
1. A weapon pose that isn't the sword pose.
2. Configurable auto reloading
3. Configurable gravity disabling
4. Configurable spread
5. Flintlock/matchlock weapons
6. Enchantable weapons
7. Custom/better sounds

**Comment by Daomephsta** [comment]
Unrelated ideas should not be one issue. That defeats the point of an issue tracker, as it makes progress on each suggestion harder to track. Open a new issue for each suggestion, and give more explanation than a 3 word phrase, I have no idea what you mean in some cases.
