### ISSUE TITLE
QuiverBow Restrung crashes on server

### ISSUE THREAD

**Issue by lordmuff** [Leviathan143/minecraft-quiverbow#21]
**Describe the bug**
When I boot up my server with QuiverBow Restrung installed, it crashes when it tries to construct the mod.

**To Reproduce**
1. Boot up server with QuiverBow Restrung installed
2. Wait for it to crash

**Expected behavior**
For it to boot up to the world.

**Crash Reports & Logs**
Crash Reports and logs attached.
[latest.log](https://github.com/Daomephsta/quiverbow-restrung/files/6126437/latest.log)
[crash-2021-03-11_17.29.22-server.txt](https://github.com/Daomephsta/quiverbow-restrung/files/6126434/crash-2021-03-11_17.29.22-server.txt)

**Version Info (please complete the following information):**
 - QuiverBow: Restrung: 0.3.1

 - Forge: 14.23.5.2855
 - Minecraft: 1.12

**Comment by Daomephsta** [comment]
Thanks.
This is likely due to the beam renderer and/or ender bow renderer not specifying they are clientside only.
