### ISSUE TITLE
Ender Rail Accelerator Cannot Be Made Functional

### ISSUE THREAD

**Issue by DarianLStephens** [Leviathan143/minecraft-quiverbow#23]
**Describe the bug**
When crafting an Ender Railgun, and filling it with Powered Rails, you get an already burned-out ERA.
Attempting to craft a burnt-out ERA in to a functional one just returns another burnt out one.

**To Reproduce**
1. Start the game
2. Spawn or craft an incomplete Ender Rail Accelerator
3. Fill with rails
4. Get burnt one
5. Try to repair it
6. Get burnt one

**Expected behavior**
To get a functional ERA when filling with rails or repairing.

**Screenshots**
Just filled the thing with rails, it's already burnt. I cannot fire it.
![2022-01-09_00 11 31](https://user-images.githubusercontent.com/15375876/148645611-e39f0a8d-4ae5-434c-964c-f819cd4ab1e0.png)

Even crafting recipes in the book show that it gives an already-burnt one.
![2022-01-09_00 11 54](https://user-images.githubusercontent.com/15375876/148645642-e0bb87f2-1595-487b-a65e-eceb5de770c4.png)

No Recipe Book entry for repairing the weapon.
![2022-01-09_00 18 50](https://user-images.githubusercontent.com/15375876/148645668-966b13b8-0d03-49a6-b907-667669835d1d.png)

Trying to manually repair it just gives you the burnt one again.
![2022-01-09_00 19 03](https://user-images.githubusercontent.com/15375876/148645684-420f0f1c-568d-48fe-be6e-0c48ede7ad0d.png)

**Crash Reports & Logs**
Not applicable.

**Version Info (please complete the following information):**
 - QuiverBow: Restrung 0.4.0
 - Forge 14.24.5.2860
 - Minecraft 1.12.2

**Additional context**
I reproduced this in a profile containing solely Quiverbow and Patchouli (The latter because the game won't load without it).

**Comment by Daomephsta** [comment]
Thanks, this is a great issue report. I've successfully reproduced the issue.
I suspect it broke with 9ee88edd22b5b0e8746dd89e84eeccde6eb847b5, the Seedling is also full when crafted, and is similarly broken. That commit caused several issues, but I thought I caught them all, evidently not. Shouldn't take long to fix in any case, probably just datapack changes.

**Comment by Daomephsta** [comment]
There's some complications with the Reinforced ERA repair recipe, but I've fixed the rest. The basic ERA repair recipe conflicts with the improved ERA repair recipe due to NBT matching being exact.

**Comment by Daomephsta** [comment]
I've flattened the basic & reinforced variants into separate items, which made fixing the repair recipes easier. I just need to do some more testing on the datafixer that automatically converts old reinforced ERAs into the new item.

**Comment by Daomephsta** [comment]
Yep, datafixer works
