### ISSUE TITLE
Non-smooth Projectiles

### ISSUE THREAD

**Issue by DarianLStephens** [Leviathan143/minecraft-quiverbow#26]
**Describe the bug**
When firing most weapons with custom projectiles, they move in a jittery way, rather than smoothly interpolating between positions like everything else in Minecraft.

**To Reproduce**
1. Spawn a projectile weapon (Such as the Coin Tosser or Snowballer. Multi-projectile weapons make it easier to see)
2. Fire it
3. Note how the projectiles move

**Expected behavior**
Smooth projectile movement, at least client-side

**Screenshots**
Still images won't help with this.

**Crash Reports & Logs**
Not applicable

**Version Info (please complete the following information):**
 - QuiverBow: Restrung 0.4.0
 - Forge 14.24.5.2860
 - Minecraft 1.12.2

**Additional context**
Tested with only Quiverbow and Patchouli.
Sorry for making so many issues, but I figure it's best to report them separately instead of in one conglomerate issue.
It's what the template suggests, too, so...

**Comment by Daomephsta** [comment]
> I figure it's best to report them separately instead of in one conglomerate issue

Absolutely. Issues are fixed individually, so it becomes harder to track which are fixed if a single issue report contains multiple unrelated issues,

**Comment by Daomephsta** [comment]
Projectile movement seems smooth to me. I'll need a video of the issue. Don't make a GIF, the compression artifacts will make the issue harder to see.

**Comment by DarianLStephens** [comment]
Huh.
Maybe I was just tired that day or something, because I'm not seeing it now.
I'll be sure to reopen the issue with a video if I happen to catch it, but for whatever reason, it seems fine now.
