### ISSUE TITLE
Unbreakable items

### ISSUE THREAD

**Issue by celophys** [Leviathan143/minecraft-quiverbow#29]
None of the weapons has durability, its normal ?

**Comment by Daomephsta** [comment]
There's an issue template for a reason, use it. This is hardly any information, I can't do anything with it.

**Comment by celophys** [comment]
Ook

**Comment by DarianLStephens** [comment]
Well that was an... interesting? Exchange.
This isn't a bug, I think they were talking about weapons never breaking and just needing to be reloaded.
This is probably part design decision, and part the original mod reusing the durability bar.
