### ISSUE TITLE
No items durability

### ISSUE THREAD

**Issue by celophys** [Leviathan143/minecraft-quiverbow#30]
**Describe the bug**
None of the items in the mod have a durability

**To Reproduce**
1 install the latest version of the mod
2 use an items more times
3 the object does not lose durability, therefore it is indestructible

**Expected behavior**
The more the object is used, the more it should lose its durability and then break

**Version Info (please complete the following information):**
 - QuiverBow: Restrung 0.4.1+ MC1.12.2
 - Forge 14.23.5.2859
 - Minecraft 1.12

**Comment by Daomephsta** [comment]
Most weapons in QB:R track remaining ammo with NBT and repurpose the durability bar to show ammo. I can change the colour of the bar if that would make it clearer?

Only the Ender Bow has actual durability, though the Seedling breaks when empty.

**Comment by celophys** [comment]
Ok, thanks for the answer !!
